#!/usr/bin/env python3

# Largely generated by chatgpt

def get_input(prompt: str) -> set[str]:
    print(prompt)
    lines = []
    while True:
        line = input()
        if not line.strip():
            break
        lines.append(line.strip())
    return {item.strip() for line in lines for item in line.splitlines()}

def print_lineset(ls: set[str]) -> None:
  print("\n".join(sorted(ls)))

# Prompt for inputs
set1 = get_input("Enter the first list of items (usually the current whitelist): ")
set2 = get_input("Enter the second list of items (usually the new list of interest): ")

# Compute set operations
intersection = set1 & set2
union = set1 | set2
difference1 = set1 - set2
difference2 = set2 - set1

# Display results
print("\nResults:")
print(f"Set 1 (Size: {len(set1)}):")
print_lineset(set1)
print(f"Set 2 (Size: {len(set2)}):")
print_lineset(set2)
print(f"Intersection (Size: {len(intersection)}):")
print_lineset(intersection)
print(f"Union (Size: {len(union)}):")
print_lineset(union)
print(f"Set 1 - Set 2 (Size: {len(difference1)})")
print_lineset(difference1)
print(f"Set 2 - Set 1 (Size: {len(difference2)})")
print_lineset(difference2)
