[server]
headless = true # This option is set to true to suppress the "Welcome to Streamlit! [blah blah blah] Email:" message, and keep streamlit from generating a .streamlit folder in my home dir with the config file that has that email address, which I find annoying. You can also run streamlit run with the --server.headless true flag if you're outside this directory but still want this behavior.
runOnSave = true # We always want to rerun when the files change, for a smooth development experience.

[browser]
gatherUsageStats = false # This makes start-up very slightly faster.
serverAddress = "localhost" # This explicitly directs the user to the correct address, localhost (which is important because we have google oauth approved for that domain) despite the fact that this is already supposed to be the default if no value is provided (which doesn't work; see https://github.com/streamlit/streamlit/issues/8629)

[theme]
base = "dark" # It seems like setting the primary color forces us to light mode, so we have to force back to dark mode (possibly this is a STREAMLIT-BUG-WORKAROUND?)
primaryColor = "#FD4844"
